export const countries = [
  { abbr: 'us', title: 'United States' },
  { abbr: 'ae', title: 'Arab Emirates' },
  { abbr: 'ar', title: 'Argentina' },
  { abbr: 'at', title: 'Austria' },
  { abbr: 'be', title: 'Belgium' },
  { abbr: 'bg', title: 'Bulgaria' },
  { abbr: 'br', title: 'Brazil' },
  { abbr: 'ca', title: 'Canada' },
  { abbr: 'ch', title: 'Switzerland' },
  { abbr: 'cn', title: 'China' },
  { abbr: 'co', title: 'Colombia' },
  { abbr: 'cu', title: 'Cuba' },
  { abbr: 'cz', title: 'Czech Republic' },
  { abbr: 'de', title: 'Germany' },
  { abbr: 'eg', title: 'Egypt' },
  { abbr: 'fr', title: 'France' },
  { abbr: 'gb', title: 'Great Britain' },
  { abbr: 'gr', title: 'Greece' },
  { abbr: 'hk', title: 'Hong Kong' },
  { abbr: 'hu', title: 'Hungary' },
  { abbr: 'id', title: 'Indonesia' },
  { abbr: 'ie', title: 'Ireland' },
  { abbr: 'il', title: 'Israel' },
  { abbr: 'in', title: 'India' },
  { abbr: 'it', title: 'Italy' },
  { abbr: 'jp', title: 'Japan' },
  { abbr: 'kr', title: 'Republic of Korea' },
  { abbr: 'lt', title: 'Lithuania' },
  { abbr: 'lv', title: 'Latvia' },
  { abbr: 'ma', title: 'Morocco' },
  { abbr: 'my', title: 'Malaysia' },
  { abbr: 'mx', title: 'Mexico' },
  { abbr: 'ng', title: 'Nigeria' },
  { abbr: 'nl', title: 'Netherlands' },
  { abbr: 'no', title: 'Norway' },
  { abbr: 'nz', title: 'New Zealand' },
  { abbr: 'ph', title: 'Philippines' },
  { abbr: 'pl', title: 'Poland' },
  { abbr: 'pt', title: 'Portugal' },
  { abbr: 'ro', title: 'Romania' },
  { abbr: 'rs', title: 'Republic of Serbia' },
  { abbr: 'ru', title: 'Russian Federation' },
  { abbr: 'sa', title: 'Saudi Arabia' },
  { abbr: 'se', title: 'Sweden' },
  { abbr: 'sg', title: 'Singapore' },
  { abbr: 'si', title: 'Slovenia' },
  { abbr: 'sk', title: 'Slovakia' },
  { abbr: 'th', title: 'Thailand' },
  { abbr: 'tr', title: 'Turkey' },
  { abbr: 'tw', title: 'Taiwan' },
  { abbr: 'ua', title: 'Ukraine' },
  { abbr: 've', title: 'Venezuela' },
  { abbr: 'za', title: 'South Africa' }
];

export const categories = [
  'Business',
  'Entertainment',
  'General',
  'Health',
  'Science',
  'Sports',
  'Technology'
];
